from apps.api.services.watsonx_service import WatsonxService

class GuardianService:
    """
    Safety layer using Granite Guardian to validate AI outputs.
    ONLY used for proposal drafts to conserve token budget.
    All other outputs rely on prompt-embedded guardrails.

    Checks for:
    - Hallucinated grant information
    - PII exposure
    - Harmful or misleading content
    - Legal compliance warnings
    """

    def __init__(self, watsonx: WatsonxService):
        self.watsonx = watsonx

    def validate_draft(self, draft_text: str, grant_context: str) -> dict:
        """
        Run Granite Guardian checks on a proposal draft.
        Returns validation result with risk assessment.

        COST: ~800 tokens per call. Only call for proposal drafts.
        """
        messages = [
            {
                "role": "system",
                "content": (
                    "You are a safety validator for AI-generated grant application content. "
                    "Check the following output for:\n"
                    "1. HALLUCINATION: Does it claim facts not present in the context?\n"
                    "2. PII: Does it expose personal information inappropriately?\n"
                    "3. LEGAL RISK: Does it make promises about grant approval or outcomes?\n"
                    "4. ACCURACY: Are amounts, dates, and eligibility claims consistent with context?\n\n"
                    "Output JSON: {\"safe\": true/false, \"risks\": [...], \"severity\": \"low|medium|high\"}"
                ),
            },
            {
                "role": "user",
                "content": f"Context:\n{grant_context[:3000]}\n\nProposal draft to validate:\n{draft_text[:3000]}",
            },
        ]

        response = self.watsonx.chat(
            messages=messages,
            params={"max_tokens": 500, "temperature": 0.0}
        )

        content = self.watsonx.get_response_text(response)

        try:
            import json
            if "```json" in content:
                content = content.split("```json")[1].split("```")[0]
            elif "```" in content:
                content = content.split("```")[1].split("```")[0]
            return json.loads(content.strip())
        except Exception:
            return {"safe": True, "risks": [], "severity": "low"}

    def sanitize_proposal(self, draft: dict) -> dict:
        """Add disclaimer and warnings to a proposal draft."""
        draft["_disclaimer"] = (
            "This proposal was generated by AI and requires human review. "
            "Verify all facts, figures, and eligibility claims before submission. "
            "The AI assistant does not guarantee grant approval."
        )
        draft["_review_status"] = "pending_human_review"
        return draft
